{
  "cveId": "CVE-2024-5629",
  "title": "Out-of-bounds read in bson module of PyMongo",
  "description": "An out-of-bounds read in the 'bson' module of PyMongo 4.6.2 or earlier allows deserialization of malformed BSON provided by a Server to raise an exception which may contain arbitrary application memory.",
  "publishedDate": "2024-06-05T14:32:56.435000+00:00",
  "lastModifiedDate": "2025-02-13T17:54:22.106000+00:00",
  "severity": "MEDIUM",
  "cvssMetrics": [
    {
      "version": "3.1",
      "vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:L/I:N/A:L",
      "baseScore": 4.7,
      "baseSeverity": "MEDIUM"
    }
  ],
  "epss": {
    "score": 0.0024,
    "percentile": 46.808
  },
  "riskScore": 31,
  "exploitationStatus": "UNKNOWN",
  "affectedSystems": {
    "cpeMatches": [],
    "vendors": ["mongodb inc"],
    "products": ["pymongo"]
  },
  "references": [
    {
      "url": "https://jira.mongodb.org/browse/PYTHON-4305",
      "source": "",
      "tags": ["release-notes"]
    },
    {
      "url": "https://lists.debian.org/debian-lts-announce/2024/06/msg00007.html",
      "source": "",
      "tags": []
    }
  ],
  "attackTechniques": [],
  "metadata": {
    "tags": ["CWE-125"],
    "requiresUserInteraction": null,
    "requiresPrivileges": null,
    "attackVector": null,
    "sources": [
      {
        "name": "CVEList",
        "url": "https://github.com/CVEProject/cvelistV5/blob/main/cves/2024/5xxx/CVE-2024-5629.json",
        "lastModified": "2025-02-13T17:54:22.106000+00:00"
      }
    ]
  }
}
