{
  "cveId": "CVE-2025-25032",
  "title": "IBM Cognos Analytics denial of service",
  "description": "IBM Cognos Analytics 11.2.0, 11.2.1, 11.2.2, 11.2.3, 11.2.4, 12.0.0, 12.0.1, 12.0.2, 12.0.3, and 12.0.4 could allow an authenticated user to cause a denial of service by sending a specially crafted request that would exhaust memory resources.",
  "publishedDate": "2025-06-11T17:26:35.867000+00:00",
  "lastModifiedDate": "2025-06-11T17:48:54.567000+00:00",
  "severity": "HIGH",
  "cvssMetrics": [
    {
      "version": "3.1",
      "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "baseScore": 7.5,
      "baseSeverity": "HIGH"
    }
  ],
  "epss": {
    "score": 0.0005,
    "percentile": 16.956
  },
  "riskScore": 48,
  "exploitationStatus": "UNKNOWN",
  "affectedSystems": {
    "cpeMatches": [],
    "vendors": ["ibm"],
    "products": ["cognos analytics"]
  },
  "references": [
    {
      "url": "https://www.ibm.com/support/pages/node/7234674",
      "source": "",
      "tags": ["vendor-advisory"]
    }
  ],
  "attackTechniques": [],
  "metadata": {
    "tags": ["CWE-770"],
    "requiresUserInteraction": null,
    "requiresPrivileges": null,
    "attackVector": null,
    "sources": [
      {
        "name": "CVEList",
        "url": "https://github.com/CVEProject/cvelistV5/blob/main/cves/2025/25xxx/CVE-2025-25032.json",
        "lastModified": "2025-06-11T17:48:54.567000+00:00"
      }
    ]
  }
}
