{
  "cveId": "CVE-2025-4969",
  "title": "Libsoup: off-by-one out-of-bounds read in find_boundary() in soup-multipart.c",
  "description": "A vulnerability was found in the libsoup package. This flaw stems from its failure to correctly verify the termination of multipart HTTP messages. This can allow a remote attacker to send a specially crafted multipart HTTP body, causing the libsoup-consuming server to read beyond its allocated memory boundaries (out-of-bounds read).",
  "publishedDate": "2025-05-21T01:44:13.820000+00:00",
  "lastModifiedDate": "2025-05-23T02:19:18.185000+00:00",
  "severity": "MEDIUM",
  "cvssMetrics": [
    {
      "version": "3.1",
      "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:L",
      "baseScore": 6.5,
      "baseSeverity": "MEDIUM"
    }
  ],
  "epss": {
    "score": 0.001,
    "percentile": 28.068
  },
  "riskScore": 39,
  "exploitationStatus": "UNKNOWN",
  "affectedSystems": {
    "cpeMatches": [],
    "vendors": ["red hat"],
    "products": [
      "red hat enterprise linux 9",
      "red hat enterprise linux 7",
      "red hat enterprise linux 10",
      "red hat enterprise linux 6",
      "red hat enterprise linux 8"
    ]
  },
  "references": [
    {
      "url": "https://access.redhat.com/security/cve/CVE-2025-4969",
      "source": "",
      "tags": ["vdb-entry", "x_refsource_REDHAT"]
    },
    {
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2367552",
      "source": "RHBZ#2367552",
      "tags": ["issue-tracking", "x_refsource_REDHAT"]
    }
  ],
  "attackTechniques": [],
  "metadata": {
    "tags": ["CWE-125"],
    "requiresUserInteraction": null,
    "requiresPrivileges": null,
    "attackVector": null,
    "sources": [
      {
        "name": "CVEList",
        "url": "https://github.com/CVEProject/cvelistV5/blob/main/cves/2025/4xxx/CVE-2025-4969.json",
        "lastModified": "2025-05-23T02:19:18.185000+00:00"
      }
    ]
  }
}
