{
  "cveId": "CVE-2025-44019",
  "title": "AVEVA PI Data Archive Uncaught Exception",
  "description": "AVEVA PI Data Archive products are vulnerable to an uncaught exception that, if \nexploited, could allow an authenticated user to shut down certain \nnecessary PI Data Archive subsystems, resulting in a denial of service. \nDepending on the timing of the crash, data present in snapshots/write \ncache may be lost.",
  "publishedDate": "2025-06-12T19:51:56.663000+00:00",
  "lastModifiedDate": "2025-06-12T20:06:50.361000+00:00",
  "severity": "HIGH",
  "cvssMetrics": [
    {
      "version": "3.1",
      "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:H",
      "baseScore": 7.1,
      "baseSeverity": "HIGH"
    }
  ],
  "epss": {
    "score": 0.0004,
    "percentile": 12.078
  },
  "riskScore": 44,
  "exploitationStatus": "UNKNOWN",
  "affectedSystems": {
    "cpeMatches": [],
    "vendors": ["aveva"],
    "products": ["pi data archive", "pi server"]
  },
  "references": [
    {
      "url": "https://www.cisa.gov/news-events/ics-advisories/icsa-25-162-07",
      "source": "",
      "tags": []
    },
    {
      "url": "https://www.aveva.com/en/support-and-success/cyber-security-updates/",
      "source": "",
      "tags": []
    },
    {
      "url": "https://my.osisoft.com/",
      "source": "",
      "tags": []
    }
  ],
  "attackTechniques": [],
  "metadata": {
    "tags": ["CWE-248"],
    "requiresUserInteraction": null,
    "requiresPrivileges": null,
    "attackVector": null,
    "sources": [
      {
        "name": "CVEList",
        "url": "https://github.com/CVEProject/cvelistV5/blob/main/cves/2025/44xxx/CVE-2025-44019.json",
        "lastModified": "2025-06-12T20:06:50.361000+00:00"
      }
    ]
  }
}
