{
  "cveId": "CVE-2024-1141",
  "title": "Glance-store: glance store access key logged in debug log level",
  "description": "A vulnerability was found in python-glance-store. The issue occurs when the package logs the access_key for the glance-store when the DEBUG log level is enabled.",
  "publishedDate": "2024-02-01T14:21:37.758000+00:00",
  "lastModifiedDate": "2024-11-24T14:50:21.545000+00:00",
  "severity": "MEDIUM",
  "cvssMetrics": [
    {
      "version": "3.1",
      "vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
      "baseScore": 5.5,
      "baseSeverity": "MEDIUM"
    }
  ],
  "epss": {
    "score": 0.0002,
    "percentile": 4.192
  },
  "riskScore": 34,
  "exploitationStatus": "UNKNOWN",
  "affectedSystems": {
    "cpeMatches": [],
    "vendors": ["red hat"],
    "products": [
      "red hat openstack platform 16.1",
      "red hat openstack platform 16.2",
      "red hat openstack platform 17.1 for rhel 9",
      "red hat openstack platform 18.0"
    ]
  },
  "references": [
    {
      "url": "https://access.redhat.com/errata/RHSA-2024:2732",
      "source": "RHSA-2024:2732",
      "tags": ["vendor-advisory", "x_refsource_REDHAT"]
    },
    {
      "url": "https://access.redhat.com/security/cve/CVE-2024-1141",
      "source": "",
      "tags": ["vdb-entry", "x_refsource_REDHAT"]
    },
    {
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2258836",
      "source": "RHBZ#2258836",
      "tags": ["issue-tracking", "x_refsource_REDHAT"]
    }
  ],
  "attackTechniques": [],
  "metadata": {
    "tags": ["CWE-779"],
    "requiresUserInteraction": null,
    "requiresPrivileges": null,
    "attackVector": null,
    "sources": [
      {
        "name": "CVEList",
        "url": "https://github.com/CVEProject/cvelistV5/blob/main/cves/2024/1xxx/CVE-2024-1141.json",
        "lastModified": "2024-11-24T14:50:21.545000+00:00"
      }
    ]
  }
}
