{
  "cveId": "CVE-2025-26699",
  "title": "CVE-2025-26699: An issue was discovered in Django 5.1 before 5.1.7, 5.0 before 5.0.13, and 4.2 before 4.2.20. The dj...",
  "description": "An issue was discovered in Django 5.1 before 5.1.7, 5.0 before 5.0.13, and 4.2 before 4.2.20. The django.utils.text.wrap() method and wordwrap template filter are subject to a potential denial-of-service attack when used with very long strings.",
  "publishedDate": "2025-03-06T00:00:00+00:00",
  "lastModifiedDate": "2025-03-19T20:03:03.946000+00:00",
  "severity": "MEDIUM",
  "cvssMetrics": [
    {
      "version": "3.1",
      "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:N/I:N/A:L",
      "baseScore": 5.0,
      "baseSeverity": "MEDIUM"
    }
  ],
  "epss": {
    "score": 0.0013,
    "percentile": 33.382
  },
  "riskScore": 34,
  "exploitationStatus": "UNKNOWN",
  "affectedSystems": {
    "cpeMatches": [],
    "vendors": ["djangoproject"],
    "products": ["django"]
  },
  "references": [
    {
      "url": "https://docs.djangoproject.com/en/dev/releases/security/",
      "source": "",
      "tags": []
    },
    {
      "url": "https://groups.google.com/g/django-announce",
      "source": "",
      "tags": []
    },
    {
      "url": "https://www.djangoproject.com/weblog/2025/mar/06/security-releases/",
      "source": "",
      "tags": []
    }
  ],
  "attackTechniques": [],
  "metadata": {
    "tags": ["CWE-770"],
    "requiresUserInteraction": null,
    "requiresPrivileges": null,
    "attackVector": null,
    "sources": [
      {
        "name": "CVEList",
        "url": "https://github.com/CVEProject/cvelistV5/blob/main/cves/2025/26xxx/CVE-2025-26699.json",
        "lastModified": "2025-03-19T20:03:03.946000+00:00"
      }
    ]
  }
}
