{
  "cveId": "CVE-2025-36539",
  "title": "AVEVA PI Data Archive Uncaught Exception",
  "description": "AVEVA PI Data Archive products \nare vulnerable to an uncaught exception that, if exploited, could allow \nan authenticated user to shut down certain necessary PI Data Archive \nsubsystems, resulting in a denial of service.",
  "publishedDate": "2025-06-12T19:56:33.320000+00:00",
  "lastModifiedDate": "2025-06-12T20:04:23.575000+00:00",
  "severity": "MEDIUM",
  "cvssMetrics": [
    {
      "version": "3.1",
      "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
      "baseScore": 6.5,
      "baseSeverity": "MEDIUM"
    }
  ],
  "epss": {
    "score": 0.0004,
    "percentile": 13.074
  },
  "riskScore": 41,
  "exploitationStatus": "UNKNOWN",
  "affectedSystems": {
    "cpeMatches": [],
    "vendors": ["aveva"],
    "products": ["pi server", "pi data archive"]
  },
  "references": [
    {
      "url": "https://www.cisa.gov/news-events/ics-advisories/icsa-25-162-07",
      "source": "",
      "tags": []
    },
    {
      "url": "https://www.aveva.com/en/support-and-success/cyber-security-updates/",
      "source": "",
      "tags": []
    }
  ],
  "attackTechniques": [],
  "metadata": {
    "tags": ["CWE-248"],
    "requiresUserInteraction": null,
    "requiresPrivileges": null,
    "attackVector": null,
    "sources": [
      {
        "name": "CVEList",
        "url": "https://github.com/CVEProject/cvelistV5/blob/main/cves/2025/36xxx/CVE-2025-36539.json",
        "lastModified": "2025-06-12T20:04:23.575000+00:00"
      }
    ]
  }
}
