{
  "cveId": "CVE-2024-4418",
  "title": "Libvirt: stack use-after-free in virnetclientioeventloop()",
  "description": "A race condition leading to a stack use-after-free flaw was found in libvirt. Due to a bad assumption in the virNetClientIOEventLoop() method, the `data` pointer to a stack-allocated virNetClientIOEventData structure ended up being used in the virNetClientIOEventFD callback while the data pointer's stack frame was concurrently being \"freed\" when returning from virNetClientIOEventLoop(). The 'virtproxyd' daemon can be used to trigger requests. If libvirt is configured with fine-grained access control, this issue, in theory, allows a user to escape their otherwise limited access. This flaw allows a local, unprivileged user to access virtproxyd without authenticating. Remote users would need to authenticate before they could access it.",
  "publishedDate": "2024-05-08T03:03:05.135000+00:00",
  "lastModifiedDate": "2025-04-11T22:03:18.932000+00:00",
  "severity": "MEDIUM",
  "cvssMetrics": [
    {
      "version": "3.1",
      "vectorString": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "baseScore": 6.2,
      "baseSeverity": "MEDIUM"
    }
  ],
  "epss": {
    "score": 0.004,
    "percentile": 59.857
  },
  "riskScore": 37,
  "exploitationStatus": "UNKNOWN",
  "affectedSystems": {
    "cpeMatches": [],
    "vendors": ["red hat"],
    "products": [
      "red hat enterprise linux 9.2 extended update support",
      "red hat enterprise linux 9",
      "red hat enterprise linux 7",
      "red hat enterprise linux 6",
      "red hat enterprise linux 8 advanced virtualization",
      "red hat enterprise linux 8"
    ]
  },
  "references": [
    {
      "url": "https://access.redhat.com/errata/RHSA-2024:4351",
      "source": "RHSA-2024:4351",
      "tags": ["vendor-advisory", "x_refsource_REDHAT"]
    },
    {
      "url": "https://access.redhat.com/errata/RHSA-2024:4432",
      "source": "RHSA-2024:4432",
      "tags": ["vendor-advisory", "x_refsource_REDHAT"]
    },
    {
      "url": "https://access.redhat.com/errata/RHSA-2024:4757",
      "source": "RHSA-2024:4757",
      "tags": ["vendor-advisory", "x_refsource_REDHAT"]
    },
    {
      "url": "https://access.redhat.com/security/cve/CVE-2024-4418",
      "source": "",
      "tags": ["vdb-entry", "x_refsource_REDHAT"]
    },
    {
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2278616",
      "source": "RHBZ#2278616",
      "tags": ["issue-tracking", "x_refsource_REDHAT"]
    }
  ],
  "attackTechniques": [],
  "metadata": {
    "tags": ["CWE-416"],
    "requiresUserInteraction": null,
    "requiresPrivileges": null,
    "attackVector": null,
    "sources": [
      {
        "name": "CVEList",
        "url": "https://github.com/CVEProject/cvelistV5/blob/main/cves/2024/4xxx/CVE-2024-4418.json",
        "lastModified": "2025-04-11T22:03:18.932000+00:00"
      }
    ]
  }
}
