{
  "cveId": "CVE-2025-5174",
  "title": "erdogant pypickle pypickle.py load deserialization",
  "description": "A vulnerability was found in erdogant pypickle up to 1.1.5 and classified as problematic. Affected by this issue is the function load of the file pypickle/pypickle.py. The manipulation leads to deserialization. Local access is required to approach this attack. The exploit has been disclosed to the public and may be used. Upgrading to version 2.0.0 is able to address this issue. The patch is identified as 14b4cae704a0bb4eb6723e238f25382d847a1917. It is recommended to upgrade the affected component.",
  "publishedDate": "2025-05-26T07:00:12.974000+00:00",
  "lastModifiedDate": "2025-05-28T17:36:21.298000+00:00",
  "severity": "MEDIUM",
  "cvssMetrics": [
    {
      "version": "3.1",
      "vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L",
      "baseScore": 5.3,
      "baseSeverity": "MEDIUM"
    },
    {
      "version": "3.0",
      "vectorString": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L",
      "baseScore": 5.3,
      "baseSeverity": "MEDIUM"
    }
  ],
  "epss": {
    "score": 0.0002,
    "percentile": 3.255
  },
  "riskScore": 39,
  "exploitationStatus": "UNKNOWN",
  "affectedSystems": {
    "cpeMatches": [],
    "vendors": ["erdogant"],
    "products": ["pypickle"]
  },
  "references": [
    {
      "url": "https://vuldb.com/?id.310262",
      "source": "VDB-310262 | erdogant pypickle pypickle.py load deserialization",
      "tags": ["vdb-entry", "technical-description"]
    },
    {
      "url": "https://vuldb.com/?ctiid.310262",
      "source": "VDB-310262 | CTI Indicators (IOB, IOC, IOA)",
      "tags": ["signature", "permissions-required"]
    },
    {
      "url": "https://vuldb.com/?submit.579157",
      "source": "Submit #579157 | erdogant pypickle 1.1.5 Insecure Deserialization",
      "tags": ["third-party-advisory"]
    },
    {
      "url": "https://github.com/erdogant/pypickle/issues/2",
      "source": "",
      "tags": ["exploit", "issue-tracking"]
    },
    {
      "url": "https://github.com/erdogant/pypickle/issues/2#issuecomment-2889146579",
      "source": "",
      "tags": ["issue-tracking"]
    },
    {
      "url": "https://github.com/erdogant/pypickle/commit/14b4cae704a0bb4eb6723e238f25382d847a1917",
      "source": "",
      "tags": ["patch"]
    },
    {
      "url": "https://github.com/erdogant/pypickle/releases/tag/2.0.0",
      "source": "",
      "tags": ["patch"]
    }
  ],
  "attackTechniques": [],
  "metadata": {
    "tags": ["CWE-502", "CWE-20"],
    "requiresUserInteraction": null,
    "requiresPrivileges": null,
    "attackVector": null,
    "sources": [
      {
        "name": "CVEList",
        "url": "https://github.com/CVEProject/cvelistV5/blob/main/cves/2025/5xxx/CVE-2025-5174.json",
        "lastModified": "2025-05-28T17:36:21.298000+00:00"
      }
    ]
  }
}
