{
  "cveId": "CVE-2024-37300",
  "title": "Globus `identity_provider` restriction ignored when used with `allow_all` in JupyterHub 5.0",
  "description": "OAuthenticator is software that allows OAuth2 identity providers to be plugged in and used with JupyterHub. JupyterHub < 5.0, when used with `GlobusOAuthenticator`, could be configured to allow all users from a particular institution only. This worked fine prior to JupyterHub 5.0, because `allow_all` did not take precedence over `identity_provider`. Since JupyterHub 5.0, `allow_all` does take precedence over `identity_provider`. On a hub with the same config, now all users will be allowed to login, regardless of `identity_provider`. `identity_provider` will basically be ignored. This is a documented change in JupyterHub 5.0, but is likely to catch many users by surprise. OAuthenticator 16.3.1 fixes the issue with JupyterHub 5.0, and does not affect previous versions. As a workaround, do not upgrade to JupyterHub 5.0 when using `GlobusOAuthenticator` in the prior configuration.",
  "publishedDate": "2024-06-12T15:20:20.363000+00:00",
  "lastModifiedDate": "2024-08-02T03:50:55.855000+00:00",
  "severity": "HIGH",
  "cvssMetrics": [
    {
      "version": "3.1",
      "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N",
      "baseScore": 8.1,
      "baseSeverity": "HIGH"
    }
  ],
  "epss": {
    "score": 0.0017,
    "percentile": 38.758
  },
  "riskScore": 40,
  "exploitationStatus": "UNKNOWN",
  "affectedSystems": {
    "cpeMatches": [],
    "vendors": ["jupyterhub"],
    "products": ["oauthenticator"]
  },
  "references": [
    {
      "url": "https://github.com/jupyterhub/oauthenticator/security/advisories/GHSA-gprj-3p75-f996",
      "source": "https://github.com/jupyterhub/oauthenticator/security/advisories/GHSA-gprj-3p75-f996",
      "tags": ["x_refsource_CONFIRM"]
    },
    {
      "url": "https://github.com/jupyterhub/oauthenticator/commit/d1aea05fa89f2beae15ab0fa0b0d071030f79654",
      "source": "https://github.com/jupyterhub/oauthenticator/commit/d1aea05fa89f2beae15ab0fa0b0d071030f79654",
      "tags": ["x_refsource_MISC"]
    },
    {
      "url": "https://jupyterhub.readthedocs.io/en/stable/howto/upgrading-v5.html#authenticator-allow-all-and-allow-existing-users",
      "source": "https://jupyterhub.readthedocs.io/en/stable/howto/upgrading-v5.html#authenticator-allow-all-and-allow-existing-users",
      "tags": ["x_refsource_MISC"]
    }
  ],
  "attackTechniques": [],
  "metadata": {
    "tags": ["CWE-863"],
    "requiresUserInteraction": null,
    "requiresPrivileges": null,
    "attackVector": null,
    "sources": [
      {
        "name": "CVEList",
        "url": "https://github.com/CVEProject/cvelistV5/blob/main/cves/2024/37xxx/CVE-2024-37300.json",
        "lastModified": "2024-08-02T03:50:55.855000+00:00"
      }
    ]
  }
}
