{
  "cveId": "CVE-2025-5175",
  "title": "erdogant pypickle pypickle.py save improper authorization",
  "description": "A vulnerability was found in erdogant pypickle up to 1.1.5. It has been classified as critical. This affects the function Save of the file pypickle/pypickle.py. The manipulation leads to improper authorization. Attacking locally is a requirement. The exploit has been disclosed to the public and may be used. Upgrading to version 2.0.0 is able to address this issue. The patch is named 14b4cae704a0bb4eb6723e238f25382d847a1917. It is recommended to upgrade the affected component.",
  "publishedDate": "2025-05-26T07:31:06.272000+00:00",
  "lastModifiedDate": "2025-05-28T17:36:15.929000+00:00",
  "severity": "MEDIUM",
  "cvssMetrics": [
    {
      "version": "3.1",
      "vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L",
      "baseScore": 5.3,
      "baseSeverity": "MEDIUM"
    },
    {
      "version": "3.0",
      "vectorString": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L",
      "baseScore": 5.3,
      "baseSeverity": "MEDIUM"
    }
  ],
  "epss": {
    "score": 0.0001,
    "percentile": 1.909
  },
  "riskScore": 39,
  "exploitationStatus": "UNKNOWN",
  "affectedSystems": {
    "cpeMatches": [],
    "vendors": ["erdogant"],
    "products": ["pypickle"]
  },
  "references": [
    {
      "url": "https://vuldb.com/?id.310263",
      "source": "VDB-310263 | erdogant pypickle pypickle.py save improper authorization",
      "tags": ["vdb-entry", "technical-description"]
    },
    {
      "url": "https://vuldb.com/?ctiid.310263",
      "source": "VDB-310263 | CTI Indicators (IOB, IOC, TTP, IOA)",
      "tags": ["signature", "permissions-required"]
    },
    {
      "url": "https://vuldb.com/?submit.579824",
      "source": "Submit #579824 | erdogant pypickle 1.1.5 File Overwrite Vulnerability",
      "tags": ["third-party-advisory"]
    },
    {
      "url": "https://github.com/erdogant/pypickle/issues/3",
      "source": "",
      "tags": ["issue-tracking"]
    },
    {
      "url": "https://github.com/erdogant/pypickle/issues/3#issuecomment-2888589652",
      "source": "",
      "tags": ["issue-tracking"]
    },
    {
      "url": "https://github.com/erdogant/pypickle/issues/3#issue-3070689116",
      "source": "",
      "tags": ["exploit", "issue-tracking"]
    },
    {
      "url": "https://github.com/erdogant/pypickle/commit/14b4cae704a0bb4eb6723e238f25382d847a1917",
      "source": "",
      "tags": ["patch"]
    },
    {
      "url": "https://github.com/erdogant/pypickle/releases/tag/2.0.0",
      "source": "",
      "tags": ["patch"]
    }
  ],
  "attackTechniques": [],
  "metadata": {
    "tags": ["CWE-285", "CWE-266"],
    "requiresUserInteraction": null,
    "requiresPrivileges": null,
    "attackVector": null,
    "sources": [
      {
        "name": "CVEList",
        "url": "https://github.com/CVEProject/cvelistV5/blob/main/cves/2025/5xxx/CVE-2025-5175.json",
        "lastModified": "2025-05-28T17:36:15.929000+00:00"
      }
    ]
  }
}
