{
  "cveId": "CVE-2025-4138",
  "title": "Bypassing extraction filter to create symlinks to arbitrary targets outside extraction directory",
  "description": "Allows the extraction filter to be ignored, allowing symlink targets to point outside the destination directory, and the modification of some file metadata.\n\n\nYou are affected by this vulnerability if using the tarfile module to extract untrusted tar archives using TarFile.extractall() or TarFile.extract() using the filter= parameter with a value of \"data\" or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter  for more information.\n\nNote that for Python 3.14 or later the default value of filter= changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.",
  "publishedDate": "2025-06-03T12:59:02.717000+00:00",
  "lastModifiedDate": "2025-06-05T14:01:24.309000+00:00",
  "severity": "HIGH",
  "cvssMetrics": [
    {
      "version": "3.1",
      "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
      "baseScore": 7.5,
      "baseSeverity": "HIGH"
    }
  ],
  "epss": {
    "score": 0.0009,
    "percentile": 26.268
  },
  "riskScore": 47,
  "exploitationStatus": "UNKNOWN",
  "affectedSystems": {
    "cpeMatches": [],
    "vendors": ["python software foundation"],
    "products": ["cpython"]
  },
  "references": [
    {
      "url": "https://github.com/python/cpython/issues/135034",
      "source": "",
      "tags": ["issue-tracking"]
    },
    {
      "url": "https://github.com/python/cpython/pull/135037",
      "source": "",
      "tags": ["patch"]
    },
    {
      "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/",
      "source": "",
      "tags": ["vendor-advisory"]
    },
    {
      "url": "https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a",
      "source": "",
      "tags": ["patch"]
    },
    {
      "url": "https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a",
      "source": "",
      "tags": ["patch"]
    },
    {
      "url": "https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f",
      "source": "",
      "tags": ["mitigation"]
    },
    {
      "url": "https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da",
      "source": "",
      "tags": ["patch"]
    },
    {
      "url": "https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01",
      "source": "",
      "tags": ["patch"]
    },
    {
      "url": "https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9",
      "source": "",
      "tags": ["patch"]
    },
    {
      "url": "https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e",
      "source": "",
      "tags": ["patch"]
    },
    {
      "url": "https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a",
      "source": "",
      "tags": ["patch"]
    },
    {
      "url": "https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1",
      "source": "",
      "tags": ["patch"]
    }
  ],
  "attackTechniques": [],
  "metadata": {
    "tags": ["CWE-22"],
    "requiresUserInteraction": null,
    "requiresPrivileges": null,
    "attackVector": null,
    "sources": [
      {
        "name": "CVEList",
        "url": "https://github.com/CVEProject/cvelistV5/blob/main/cves/2025/4xxx/CVE-2025-4138.json",
        "lastModified": "2025-06-05T14:01:24.309000+00:00"
      }
    ]
  }
}
