{
  "cveId": "CVE-2025-32051",
  "title": "Libsoup: segmentation fault when parsing malformed data uri",
  "description": "A flaw was found in libsoup. The libsoup soup_uri_decode_data_uri() function may crash when processing malformed data URI. This flaw allows an attacker to cause a denial of service (DoS).",
  "publishedDate": "2025-04-03T13:36:50.776000+00:00",
  "lastModifiedDate": "2025-05-27T22:34:23.708000+00:00",
  "severity": "MEDIUM",
  "cvssMetrics": [
    {
      "version": "3.1",
      "vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "baseScore": 5.9,
      "baseSeverity": "MEDIUM"
    }
  ],
  "epss": {
    "score": 0.0006,
    "percentile": 18.823
  },
  "riskScore": 38,
  "exploitationStatus": "UNKNOWN",
  "affectedSystems": {
    "cpeMatches": [],
    "vendors": ["red hat"],
    "products": [
      "red hat enterprise linux 9",
      "red hat enterprise linux 7",
      "red hat enterprise linux 10",
      "red hat enterprise linux 6",
      "red hat enterprise linux 8"
    ]
  },
  "references": [
    {
      "url": "https://access.redhat.com/security/cve/CVE-2025-32051",
      "source": "",
      "tags": ["vdb-entry", "x_refsource_REDHAT"]
    },
    {
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2357068",
      "source": "RHBZ#2357068",
      "tags": ["issue-tracking", "x_refsource_REDHAT"]
    }
  ],
  "attackTechniques": [],
  "metadata": {
    "tags": ["CWE-754"],
    "requiresUserInteraction": null,
    "requiresPrivileges": null,
    "attackVector": null,
    "sources": [
      {
        "name": "CVEList",
        "url": "https://github.com/CVEProject/cvelistV5/blob/main/cves/2025/32xxx/CVE-2025-32051.json",
        "lastModified": "2025-05-27T22:34:23.708000+00:00"
      }
    ]
  }
}
