{
  "cveId": "CVE-2025-2312",
  "title": "cifs.upcall  makes an upcall to the wrong namespace in containerized environments",
  "description": "A flaw was found in cifs-utils. When trying to obtain Kerberos credentials, the cifs.upcall program from the cifs-utils package makes an upcall to the wrong namespace in containerized environments. This issue may lead to disclosing sensitive data from the host's Kerberos credentials cache.",
  "publishedDate": "2025-03-25T18:08:02.848000+00:00",
  "lastModifiedDate": "2025-03-25T18:23:15.943000+00:00",
  "severity": "MEDIUM",
  "cvssMetrics": [
    {
      "version": "3.1",
      "vectorString": "CVSS:3.1/AV:L/AC:H/PR:N/UI:N/S:C/C:H/I:N/A:N",
      "baseScore": 5.9,
      "baseSeverity": "MEDIUM"
    }
  ],
  "epss": {
    "score": 0.0002,
    "percentile": 3.373
  },
  "riskScore": 36,
  "exploitationStatus": "UNKNOWN",
  "affectedSystems": {
    "cpeMatches": [],
    "vendors": ["cifs-utils"],
    "products": ["cifs-utils"]
  },
  "references": [
    {
      "url": "https://git.samba.org/?p=cifs-utils.git;a=commit;h=89b679228cc1be9739d54203d28289b03352c174",
      "source": "",
      "tags": ["patch"]
    },
    {
      "url": "https://web.git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/fs/smb?id=db363b0a1d9e6b9dc556296f1b1007aeb496a8cf",
      "source": "",
      "tags": ["patch"]
    }
  ],
  "attackTechniques": [],
  "metadata": {
    "tags": ["CWE-488"],
    "requiresUserInteraction": null,
    "requiresPrivileges": null,
    "attackVector": null,
    "sources": [
      {
        "name": "CVEList",
        "url": "https://github.com/CVEProject/cvelistV5/blob/main/cves/2025/2xxx/CVE-2025-2312.json",
        "lastModified": "2025-03-25T18:23:15.943000+00:00"
      }
    ]
  }
}
